Repository betagouv/recommandations-collaboratives, pull requests merged in 2025-02, with the labels that each got.

#980 [chore] Some improvements
  recoco/apps/geomatics/rest.py
  recoco/apps/projects/context_processors.py
  recoco/apps/projects/serializers.py
  recoco/apps/projects/views/__init__.py
  recoco/apps/projects/views/rest.py
  recoco/apps/resources/rest.py
Labels: backend

#1006 Correction d'un crash de page sur l'état des lieux en cas de section de question vide
  recoco/apps/projects/tests/test_projects.py
  recoco/apps/survey/templates/survey/widgets/qs_summary_card.html
Labels: backend, bloquant

#1043 [feat] Lors du click d'une ressource pré-suggérée redirection vers le pousse-reco
  recoco/apps/projects/templates/projects/project/fragments/action_list_item.html
Labels: tests missing
